pipeline {
  agent any

  tools{
    maven 'maven 3.6.1'
  }

  stages{

    stage("build"){
      when{
        changeset "**/worker/**"
      }
      steps{
        echo 'Compiling worker app'
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }

    stage("test"){
      when{
        changeset "**/worker/**"
      }
      steps{
        echo 'Running Unit Tets on worker app'
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }

    stage("package"){
      when{
        branch 'main'
        changeset "**/worker/**"
      }
      steps{
        echo 'Packaging worker app'
        dir('worker'){
          sh 'mvn package'
        }
      }
    }
  }

  post{
    always{

      echo 'Building multibranch pipeline for worker is completed..'
    }
    failiure{
      slackSend (channel: "kdemo-devops", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    success{
      archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      slackSend (channel: "kdemo-devops", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
  }
}
